apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: nnksantosh/my-app:eb70c147bab4e33a25dc4be666945b1d9dc62d99
        ports:
        - containerPort: 3000
